erDiagram
  CONTESTS {
    VARCHAR(40) id PK
    VARCHAR(100) name
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  GRADES {
    VARCHAR(40) id PK
    VARCHAR(100) name
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  SCHOOLS {
    VARCHAR(40) id PK
    VARCHAR(200) name
    VARCHAR(150) province
    VARCHAR(150) district
    VARCHAR(150) sub_district
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  STUDENTS {
    VARCHAR(40) id PK
    VARCHAR(100) prefix
    VARCHAR(100) first_name_th
    VARCHAR(100) last_name_th
    VARCHAR(100) first_name_en
    VARCHAR(100) last_name_en
    VARCHAR(40) grade_id FK
    VARCHAR(40) school_id FK
    VARCHAR(40) contest_id FK
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  SYSTEMS {
    VARCHAR(100) name PK
    BOOLEAN is_online
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  USERS {
    VARCHAR(40) id PK
    VARCHAR(100) username
    VARCHAR(100) prefix
    VARCHAR(100) first_name
    VARCHAR(100) last_name
    VARCHAR(20) phone_number
    ENUM role
    ENUM status
    TIMESTAMP created_at
    TIMESTAMP updated_at
  }

  USER_COORDINATORS {
    VARCHAR(40) user_id PK,FK
    TINYTEXT position
    TEXT position
    VARCHAR(40) school_id FK
  }

  USERS ||--o| USER_COORDINATORS : is
  USER_COORDINATORS }o--|| SCHOOLS : work_in
  STUDENTS }o--|| SCHOOLS : study_in
  STUDENTS }o--|| GRADES : study_in
  STUDENTS }o--|| CONTESTS : challenge_in
