name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Extract fonts from zip
        run: unzip fonts.zip -d fonts

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: full-report.tex
          compiler: xelatex
          extra_fonts: fonts/*.ttf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: full-report.pdf
