name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract fonts from zip
        run: unzip fonts.zip

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: full-report.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: full-report.pdf
