name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract fonts from zip
        run: unzip fonts.zip

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: full-report.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ./build/full-report.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/full-report.pdf
